language: python
python: 3.7
jobs:
  include:
    - env: TOXENV=pre-commit
    - stage: Create GitHub release
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install jq
      install:
        - pip install yq
        - pip install tox
      before_deploy:
        - export AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
        - export GIT_TAG="$(yq -r .metadata.template_version shell-definition.yaml)"
        - git config --local user.name $AUTHOR_NAME
        - git config --local user.email $AUTHOR_EMAIL
        - git tag $GIT_TAG
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          secure: "Ra25juZ1WbzDCKcnHjAr7KMgyvebq72aivWvY1koibXU999MGk+nfcPTsAC5kH+11NnAU/fzsNZ3y51IEv7c7pOh0G1836xVXhccOeEKMR6aTj4BnVi3V8LjUhJ4Xg05vGzTLbrUUR4GArhuKb6DjedUMVbhmsIUVbUlnNRChKX6SC8QXlss2Ft5EhkRI8rwx4QaUEe8p48nn3iJXSxTbk5aA8z04a8hNTZOYDVXcQlM6pqrWAZZAuFOcs6ifTxsHN53T9H1zXK8PyW43UdSziHIZLPEYnCQDsNO1fDh0Iohbycn1o6hN7u6DeI0dqdzBwb5bvo9/XSqRvo+BVeqbqY4ItaCCyyigVR4w823j3eFZT3yIBWx3PKv/gSLLsSSVifltp4bBrA7anNTrhgBJ/NvKaRaMsVzlKSHqHI3xHGIYZVGUl0Oghv0L+ShJmL7YAEMZV7D8QAth6kZ3UU3YPSOZ6tdhJ5pPKOfwpxU6rIX74Gg5EW++JLgeJa/CjhpoN+sEuB8fG2n8Ly/gfNExxzQQDSjLdGi8p3U9QKCHRUXHBtqzqtKKrJ/SO08GfKRMDM+UxcBYwbEVfBpSdkDBo/OIF79LfJo1E7rq8QxI8v+OK8MmSVUEpHj/ZTaZ+C+9mPm6xQxus3e8Bfeghl1nCqFxti9hJ1sxwaQxofJe+4="
        file_glob: true
        file: dist/*.zip
        name: DUT Shell 2G $GIT_TAG
        target_commitish: master
        on:
          branch: master
    - stage: Check version
      language: bash
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install jq
      install:
        - pip install yq
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_PULL_REQUEST_BRANCH
      script: "! diff <(yq .metadata.template_version shell-definition.yaml) <(git show master:shell-definition.yaml > tmp.yaml && yq .metadata.template_version tmp.yaml)"

install:
  - pip install tox

script: tox

stages:
  - name: Check version
    if: branch = master AND type = pull_request
  - name: Test
  - name: Create GitHub release
    if: branch = master AND type != pull_request
