name: update release
on: workflow_dispatch
jobs:
  shell-ci:
    uses: QualiSystems/.github/.github/workflows/shell-py-37-39.yml@master
  github-release:
    needs: shell-ci
    uses: ./.github/workflows/create-release.yml
    with:
      update: true
